---
- name: Install AWS 
  hosts: ubuntu
  become: true

  tasks:
  - name: Install AWS CLI
    shell: >
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" &&
      unzip awscliv2.zip &&
      ./aws/install -i /usr/local/aws-cli -b /usr/local/bin
    when: not aws_cli_installed.stat.exists
